vim.cmd("source ~/.config/nvim/plugins.vim")

require("jelle.opts")
require("jelle.tree")
require("jelle.search")
require("jelle.git")
require("jelle.lsp")
require("jelle.cmp")
require("jelle.treesitter")
require("jelle.statusline")
require("jelle.vimwiki")
